services:
  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_DATABASE: runrush_dev
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  app:
    image: dnjsxo0616/runrush-app:latest
    container_name: spring-app
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  mysql_data: