services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    command: --innodb_buffer_pool_size=64M --max_connections=30
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    restart: no

  app:
    image: dnjsxo0616/runrush-app:latest  # build 대신 image 사용
    container_name: spring-app
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    env_file:
      - runrush.env  # .env 대신 runrush.env
    command: [ "java", "-Xmx300m", "-Xms300m", "-jar", "app.jar" ]
    networks:
      - app-network
    restart: no

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge